apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  type: LoadBalancer
  ports:
    - name: "8891"
      port: 8891
      targetPort: 8891
      nodePort: 30163
      protocol: TCP
  selector:
    io.kompose.service: gateway
status:
  loadBalancer: {}
